### PR TITLE
fix CI (euslisp-dfsg check) for eus10

### PR DESCRIPTION
**Pull request by k-okada**
add patches to fix dfsg-patches for eus10

### CODE REVIEW

**Comment by Affonso-Gui** [comment]
Thanks! The build got fixed for ARM64.
Now ARM32 seems to be failing to do `apt update` ...

https://github.com/Affonso-Gui/EusLisp/actions/runs/4551036079/jobs/8041670626

**Comment by k-okada** [comment]
jessie have been moved to archive directory ?
https://unix.stackexchange.com/questions/508724/failed-to-fetch-jessie-backports-repository
--
◉ Kei Okada



2023年3月30日(木) 9:39 Affonso, Guilherme ***@***.***>:

**Comment by Affonso-Gui** [comment]
Possible, but the change referenced in the post is from a few years back, and the arm32 tests seem to be passing until recently..

**Comment by k-okada** [comment]
Even if there was an announcement a few years ago , removing directory did
not happen immediately, it's up to the mirror maintainer .
they have changed README last week https://deb.debian.org/debian/, may be
they removed old repository at that time.

--
◉ Kei Okada



2023年3月30日(木) 11:35 Affonso, Guilherme ***@***.***>:

**Comment by Affonso-Gui** [comment]
:+1:

**Pull request merged**
